# Generated by Django 5.2.17 on 2026-09-16 03:53

import django.db.models.deletion
import django.utils.timezone
import shared.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_twofactordevice_loginattempt_recoverycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('npc', 'Nepal Pharmacy Council'), ('nmc', 'Nepal Medical Council'), ('nnc', 'Nepal Nursing Council'), ('nhpc', 'Nepal Health Professional Council'), ('other', 'Other')], max_length=10)),
                ('registration_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Awaiting verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_note', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'type', 'registration_number'), name='identity_unique_credential')],
            },
        ),
    ]
