# Generated by Django 5.2.17 on 2026-09-16 15:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import shared.ids
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_branch_licence_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('hospital', 'Hospital or clinic'), ('government', 'Government body')], default='business', max_length=20)),
                ('is_supplier', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('name_ne', models.CharField(blank=True, max_length=200)),
                ('pan', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='PAN must be exactly 9 digits.', regex='^\\d{9}$')], verbose_name='PAN')),
                ('is_vat_registered', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('dda_licence_number', models.CharField(blank=True, max_length=50)),
                ('dda_licence_expiry', models.DateField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Zero means no credit is extended.', max_digits=18)),
                ('credit_days', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'parties',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'phone'], name='parties_par_tenant__f5bd07_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='parties_unique_name'), models.CheckConstraint(condition=models.Q(('is_supplier', True), ('is_customer', True), _connector='OR'), name='parties_must_be_supplier_or_customer')],
            },
        ),
    ]
