# Generated by Django 5.2.17 on 2026-09-16 05:01

import django.db.models.deletion
import django.utils.timezone
import shared.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_row_level_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_code', models.CharField(max_length=100, unique=True)),
                ('is_killed', models.BooleanField(default=False, help_text='Off for everyone, whatever their plan says.')),
                ('rollout_percent', models.PositiveSmallIntegerField(default=100, help_text='Share of accounts the feature reaches, chosen stably per account.')),
                ('allowed_tenants', models.JSONField(blank=True, default=list)),
                ('denied_tenants', models.JSONField(blank=True, default=list)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_ne', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('status', models.CharField(choices=[('alpha', 'alpha'), ('beta', 'beta'), ('ga', 'ga'), ('deprecated', 'deprecated')], default='ga', max_length=12)),
                ('is_core', models.BooleanField(default=False, help_text='Always installed; cannot be disabled.')),
                ('depends_on', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_ne', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('kind', models.CharField(choices=[('boolean', 'boolean'), ('limit', 'limit'), ('quota', 'quota')], default='boolean', max_length=10)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='entitlements.module')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FeatureGrant',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('plan', 'Included in the plan'), ('addon', 'Purchased add-on'), ('override', 'Manual override')], max_length=10)),
                ('value', models.JSONField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entitlements.feature')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'feature'], name='entitlement_tenant__6a74b6_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'feature', 'source'), name='entitlements_unique_grant_per_source')],
            },
        ),
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('disabled_reason', models.CharField(blank=True, max_length=200)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='entitlements.module')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'module'), name='entitlements_unique_tenant_module')],
            },
        ),
        migrations.CreateModel(
            name='UsageMeter',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('value', models.BigIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'metric', '-period_start'], name='entitlement_tenant__36735b_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'metric', 'period_start'), name='entitlements_unique_meter_period')],
            },
        ),
    ]
