# Generated by Django 5.2.17 on 2026-09-16 04:04

import django.db.models.deletion
import django.utils.timezone
import shared.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_row_level_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChainHead',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.BigIntegerField(default=0)),
                ('last_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='audit_one_chain_head_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.BigIntegerField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Changed'), ('archive', 'Archived'), ('restore', 'Restored'), ('delete', 'Deleted'), ('login', 'Signed in'), ('logout', 'Signed out'), ('export', 'Exported'), ('print', 'Printed'), ('reprint', 'Reprinted'), ('view_sensitive', 'Viewed sensitive data'), ('override', 'Overrode a rule'), ('void', 'Voided'), ('permission_change', 'Changed access'), ('settings_change', 'Changed settings'), ('impersonation_start', 'Support access started'), ('impersonation_end', 'Support access ended')], db_index=True, max_length=30)),
                ('actor_label', models.CharField(blank=True, max_length=200)),
                ('entity_type', models.CharField(blank=True, help_text='app_label.ModelName', max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('entity_label', models.CharField(blank=True, max_length=300)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-sequence'],
                'indexes': [models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='audit_audit_tenant__0af437_idx'), models.Index(fields=['tenant', 'actor', '-created_at'], name='audit_audit_tenant__487311_idx'), models.Index(fields=['tenant', '-created_at'], name='audit_audit_tenant__eab6aa_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'sequence'), name='audit_unique_sequence_per_tenant')],
            },
        ),
    ]
