# Generated by Django 5.2.17 on 2026-09-16 11:57

import django.db.models.deletion
import django.utils.timezone
import shared.ids
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_unit_plural_label'),
        ('tenancy', '0002_row_level_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='As printed on the pack.', max_length=60)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Landed cost of one base unit.', max_digits=18)),
                ('status', models.CharField(choices=[('available', 'Available'), ('quarantined', 'Quarantined'), ('expired', 'Expired'), ('recalled', 'Recalled'), ('damaged', 'Damaged')], db_index=True, default='available', max_length=20)),
                ('status_reason', models.CharField(blank=True, max_length=300)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'batches',
                'ordering': ['expiry_date', 'number'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='catalog.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['item', 'batch'],
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('opening', 'Opening stock'), ('receipt', 'Goods received'), ('sale', 'Sold'), ('sale_return', 'Returned by customer'), ('purchase_return', 'Returned to supplier'), ('transfer_out', 'Transferred out'), ('transfer_in', 'Transferred in'), ('adjustment', 'Adjustment'), ('write_off', 'Written off'), ('reversal', 'Reversal of an earlier entry')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('document_type', models.CharField(blank=True, max_length=60)),
                ('document_id', models.CharField(blank=True, max_length=64)),
                ('document_number', models.CharField(blank=True, max_length=60)),
                ('document_line_id', models.CharField(blank=True, max_length=64)),
                ('occurred_on', models.DateField(help_text='The business date, which may not be today.')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.location')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='inventory.stockledgerentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'stock ledger entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['tenant', 'item', 'expiry_date'], name='inventory_b_tenant__373691_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('tenant', 'item', 'number'), name='inventory_unique_batch_per_item'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='inventory_batch_cost_not_negative'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['tenant', 'item', 'branch'], name='inventory_s_tenant__aa4672_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('tenant', 'location', 'item', 'batch'), name='inventory_one_balance_per_batch_location', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['tenant', 'item', '-created_at'], name='inventory_s_tenant__b1ff9c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['tenant', 'branch', 'item', 'batch'], name='inventory_s_tenant__f817c9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['tenant', 'document_type', 'document_id'], name='inventory_s_tenant__a88b83_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['tenant', 'occurred_on'], name='inventory_s_tenant__30e565_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='inventory_movement_is_not_zero'),
        ),
    ]
