# Generated by Django 5.2.17 on 2026-09-16 15:44

import django.db.models.deletion
import django.utils.timezone
import shared.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_branch_licence_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('name_ne', models.CharField(blank=True, max_length=200)),
                ('council', models.CharField(choices=[('nmc', 'Nepal Medical Council'), ('ndc', 'Nepal Dental Council'), ('nhpc', 'Nepal Health Professional Council'), ('nayc', 'Nepal Ayurvedic Medical Council'), ('other', 'Other')], default='nmc', max_length=10)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('speciality', models.CharField(blank=True, max_length=120)),
                ('workplace', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('verified_note', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'name'], name='practitione_tenant__fc5bf8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('registration_number', ''), _negated=True), fields=('tenant', 'council', 'registration_number'), name='practitioners_unique_registration')],
            },
        ),
    ]
