# Generated by Django 5.2.17 on 2026-09-16 11:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import shared.ids
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax', '0001_initial'),
        ('tenancy', '0002_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('name_ne', models.CharField(blank=True, max_length=50)),
                ('allows_fractions', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('name_ne', models.CharField(blank=True, max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.itemcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'item categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(help_text='Internal code or SKU.')),
                ('name', models.CharField(max_length=200)),
                ('name_ne', models.CharField(blank=True, max_length=200)),
                ('item_type', models.CharField(choices=[('medicine', 'Medicine'), ('device', 'Medical device'), ('consumable', 'Consumable'), ('cosmetic', 'Cosmetic'), ('general', 'General goods'), ('service', 'Service')], default='medicine', max_length=20)),
                ('is_batch_tracked', models.BooleanField(default=True, help_text='Stock is held per batch. Required for anything with an expiry.')),
                ('is_expiry_tracked', models.BooleanField(default=True)),
                ('allow_loose_sale', models.BooleanField(default=True, help_text='Single base units may be sold, such as four tablets out of a strip.')),
                ('hs_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tax_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.taxcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.itemcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factor', models.DecimalField(decimal_places=6, help_text='Base units in one of these.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('is_purchase_default', models.BooleanField(default=False)),
                ('is_sale_default', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='catalog.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.unitofmeasure')),
            ],
            options={
                'ordering': ['item', 'factor'],
            },
        ),
        migrations.CreateModel(
            name='ItemBarcode',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='catalog.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('item_unit', models.ForeignKey(blank=True, help_text='Which pack this barcode is printed on. Blank means the base unit.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='catalog.itemunit')),
            ],
            options={
                'ordering': ['item', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('name_ne', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('licence_number', models.CharField(blank=True, max_length=60)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.manufacturer'),
        ),
        migrations.AddField(
            model_name='item',
            name='base_unit',
            field=models.ForeignKey(help_text='The smallest unit stock is counted in. Everything converts to this.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.unitofmeasure'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='catalog_unique_category_code'),
        ),
        migrations.AddIndex(
            model_name='itembarcode',
            index=models.Index(fields=['tenant', 'code'], name='catalog_ite_tenant__e4b2b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='itembarcode',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='catalog_unique_barcode_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='manufacturer',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='catalog_unique_manufacturer_name'),
        ),
        migrations.AddConstraint(
            model_name='itemunit',
            constraint=models.UniqueConstraint(fields=('tenant', 'item', 'unit'), name='catalog_unique_item_unit'),
        ),
        migrations.AddConstraint(
            model_name='itemunit',
            constraint=models.CheckConstraint(condition=models.Q(('factor__gt', 0)), name='catalog_factor_positive'),
        ),
        migrations.AddConstraint(
            model_name='itemunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_purchase_default', True)), fields=('tenant', 'item'), name='catalog_one_purchase_default'),
        ),
        migrations.AddConstraint(
            model_name='itemunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_sale_default', True)), fields=('tenant', 'item'), name='catalog_one_sale_default'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'name'], name='catalog_ite_tenant__1d8955_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='catalog_unique_item_code'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('is_expiry_tracked', False), ('is_batch_tracked', True), _connector='OR'), name='catalog_expiry_requires_batches'),
        ),
    ]
