# Generated by Django 5.2.17 on 2026-09-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_row_level_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasure',
            name='name_plural',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
