# Generated by Django 5.2.17 on 2026-09-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_unit_plural_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='MRP'),
        ),
    ]
