# Generated by Django 5.2.17 on 2026-09-15 18:35

import django.db.models.deletion
import django.utils.timezone
import shared.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_ne', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_ne', models.CharField(blank=True, max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='geo.province')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocalLevel',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('name_ne', models.CharField(blank=True, max_length=120)),
                ('type', models.CharField(choices=[('metropolitan', 'Metropolitan City'), ('sub_metropolitan', 'Sub-Metropolitan City'), ('municipality', 'Municipality'), ('rural_municipality', 'Rural Municipality')], max_length=20)),
                ('ward_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_levels', to='geo.district')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('district', 'name'), name='geo_unique_local_level_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('province', 'name'), name='geo_unique_district_name'),
        ),
    ]
