# Generated by Django 5.2.17 on 2026-09-16 15:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import shared.ids
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_unit_plural_label'),
        ('inventory', '0002_row_level_security_and_append_only'),
        ('parties', '0002_row_level_security'),
        ('tenancy', '0003_branch_licence_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=16)),
                ('number', models.CharField(blank=True, help_text='Assigned when issued.', max_length=60)),
                ('fiscal_year', models.CharField(blank=True, max_length=9)),
                ('invoice_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=300)),
                ('prices_include_tax', models.BooleanField(default=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('rounding_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='parties.party')),
                ('location', models.ForeignKey(help_text='The counter the sale was made from.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('base_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Price of one pack.', max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('tax_percentage', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.unitofmeasure')),
            ],
            options={
                'ordering': ['invoice', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLineBatch',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.batch')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.salesinvoiceline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['line', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['tenant', 'branch', '-invoice_date'], name='sales_sales_tenant__713154_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['tenant', 'customer_phone'], name='sales_sales_tenant__0fbc57_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['tenant', 'fiscal_year'], name='sales_sales_tenant__7f3f9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('tenant', 'branch', 'number'), name='sales_unique_invoice_number_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='sales_line_rate_not_negative'),
        ),
        migrations.AddIndex(
            model_name='salesinvoicelinebatch',
            index=models.Index(fields=['tenant', 'batch'], name='sales_sales_tenant__e453d5_idx'),
        ),
    ]
