# Generated by Django 5.2.17 on 2026-09-16 16:29

import django.db.models.deletion
import django.utils.timezone
import shared.ids
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_default_mrp'),
        ('inventory', '0002_row_level_security_and_append_only'),
        ('sales', '0002_row_level_security'),
        ('tenancy', '0003_branch_licence_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('cancellation', 'Cancellation of an invoice'), ('return', 'Goods returned by the customer'), ('adjustment', 'Price adjustment')], max_length=20)),
                ('reason_code', models.CharField(choices=[('changed_mind', 'Customer changed their mind'), ('wrong_item', 'Wrong item supplied'), ('damaged', 'Damaged'), ('expired', 'Expired or near expiry'), ('adverse_reaction', 'Adverse reaction'), ('rate_difference', 'Rate difference'), ('invoice_cancelled', 'Invoice cancelled'), ('other', 'Other')], default='other', max_length=20)),
                ('reason', models.CharField(max_length=300)),
                ('destination', models.CharField(choices=[('quarantine', 'Quarantine, pending inspection'), ('sellable', 'Back on the shelf')], default='quarantine', max_length=20)),
                ('number', models.CharField(blank=True, help_text='Assigned when issued.', max_length=60)),
                ('fiscal_year', models.CharField(blank=True, max_length=9)),
                ('note_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('prices_include_tax', models.BooleanField(default=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('rounding_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.branch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.salesinvoice')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-note_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteLine',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('base_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('tax_percentage', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.batch')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.creditnote')),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_lines', to='sales.salesinvoiceline')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.unitofmeasure')),
            ],
            options={
                'ordering': ['credit_note', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['tenant', 'branch', '-note_date'], name='sales_credi_tenant__fcb8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['tenant', 'fiscal_year'], name='sales_credi_tenant__6d4aea_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('tenant', 'branch', 'number'), name='sales_unique_credit_note_number_per_branch'),
        ),
        migrations.AddIndex(
            model_name='creditnoteline',
            index=models.Index(fields=['tenant', 'batch'], name='sales_credi_tenant__360df2_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditnoteline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_credit_line_quantity_positive'),
        ),
    ]
