# Generated by Django 5.2.17 on 2026-09-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_credit_note_row_level_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
