# Generated by Django 5.2.17 on 2026-09-16 11:45

import django.db.models.deletion
import django.utils.timezone
import shared.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_ne', models.CharField(blank=True, max_length=100)),
                ('treatment', models.CharField(choices=[('standard', 'Taxable at the standard rate'), ('exempt', 'Exempt from VAT'), ('zero_rated', 'Zero-rated')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('guidance', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'tax categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='tax.taxcategory')),
            ],
            options={
                'ordering': ['category', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('category', 'effective_from'), name='tax_one_rate_per_start_date'), models.CheckConstraint(condition=models.Q(('percentage__gte', 0)), name='tax_rate_is_not_negative'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='tax_rate_period_is_not_backwards')],
            },
        ),
    ]
