# Generated by Django 5.2.17 on 2026-09-16 19:46

import django.db.models.deletion
import django.utils.timezone
import kernel.settings.registry
import shared.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_branch_licence_authority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingValue',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('scope', models.CharField(choices=[(kernel.settings.registry.Scope['TENANT'], kernel.settings.registry.Scope['TENANT']), (kernel.settings.registry.Scope['LEGAL_ENTITY'], kernel.settings.registry.Scope['LEGAL_ENTITY']), (kernel.settings.registry.Scope['BRANCH'], kernel.settings.registry.Scope['BRANCH']), (kernel.settings.registry.Scope['USER'], kernel.settings.registry.Scope['USER'])], max_length=20)),
                ('scope_id', models.CharField(blank=True, help_text='Empty when the value applies to the whole account.', max_length=64)),
                ('value', models.TextField()),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['key', 'scope'],
                'indexes': [models.Index(fields=['tenant', 'key'], name='settings_se_tenant__0a785a_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key', 'scope', 'scope_id'), name='settings_one_value_per_scope'), models.CheckConstraint(condition=models.Q(models.Q(('scope', 'tenant'), ('scope_id', '')), models.Q(('scope', 'tenant'), _negated=True), _connector='OR'), name='settings_account_wide_values_have_no_target'), models.CheckConstraint(condition=models.Q(('scope__in', ['legal_entity', 'branch', 'user']), ('scope_id', ''), _negated=True), name='settings_narrow_values_name_their_target')],
            },
        ),
    ]
