# Generated by Django 5.2.17 on 2026-09-16 15:44

import django.db.models.deletion
import django.utils.timezone
import shared.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_item_default_mrp'),
        ('parties', '0002_row_level_security'),
        ('sales', '0002_row_level_security'),
        ('tenancy', '0003_branch_licence_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRule',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.CharField(choices=[('ka', 'Samuha Ka (समूह क)'), ('kha', 'Samuha Kha (समूह ख)'), ('ga', 'Samuha Ga (समूह ग)'), ('unclassified', 'Not yet classified')], max_length=20)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('requires_prescriber_registration', models.BooleanField(default=False, help_text="The prescriber's council registration must be recorded.")),
                ('requires_register_entry', models.BooleanField(default=False, help_text='A separate statutory register entry, as for narcotics.')),
                ('requires_pharmacist', models.BooleanField(default=False, help_text='A registered pharmacist must dispense it personally.')),
                ('max_days_supply', models.PositiveSmallIntegerField(default=0)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('source_note', models.CharField(blank=True, help_text='Which notice or Act this comes from.', max_length=300)),
            ],
            options={
                'ordering': ['schedule', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='MedicineProfile',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generic_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('strength', models.CharField(blank=True, help_text='Such as 500mg.', max_length=60)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('suspension', 'Suspension'), ('injection', 'Injection'), ('ointment', 'Ointment or cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('powder', 'Powder'), ('other', 'Other')], default='tablet', max_length=20)),
                ('route', models.CharField(blank=True, max_length=60)),
                ('schedule', models.CharField(choices=[('ka', 'Samuha Ka (समूह क)'), ('kha', 'Samuha Kha (समूह ख)'), ('ga', 'Samuha Ga (समूह ग)'), ('unclassified', 'Not yet classified')], db_index=True, default='unclassified', max_length=20)),
                ('dda_registration_number', models.CharField(blank=True, max_length=60)),
                ('marketing_authorisation_holder', models.CharField(blank=True, max_length=200)),
                ('requires_cold_chain', models.BooleanField(default=False)),
                ('is_narcotic', models.BooleanField(default=False, help_text='Held in a locked cabinet and entered in the narcotic register.')),
                ('storage_note', models.CharField(blank=True, max_length=200)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='catalog.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['generic_name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.CharField(blank=True, max_length=20)),
                ('patient_phone', models.CharField(blank=True, max_length=16)),
                ('prescribed_on', models.DateField()),
                ('valid_until', models.DateField(blank=True, help_text='After this a fresh prescription is needed.', null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=300)),
                ('attachment_reference', models.CharField(blank=True, max_length=300)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='sales.salesinvoice')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='parties.party')),
            ],
            options={
                'ordering': ['-prescribed_on'],
            },
        ),
    ]
