# Generated by Django 5.2.17 on 2026-09-16 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('practitioners', '0001_initial'),
        ('tenancy', '0003_branch_licence_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='practitioners.practitioner'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddConstraint(
            model_name='schedulerule',
            constraint=models.UniqueConstraint(fields=('schedule', 'effective_from'), name='pharmacy_one_rule_per_start_date'),
        ),
        migrations.AddIndex(
            model_name='medicineprofile',
            index=models.Index(fields=['tenant', 'generic_name'], name='pharmacy_me_tenant__addf63_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineprofile',
            index=models.Index(fields=['tenant', 'schedule'], name='pharmacy_me_tenant__05edc8_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['tenant', '-prescribed_on'], name='pharmacy_pr_tenant__0354a7_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['tenant', 'patient_phone'], name='pharmacy_pr_tenant__2f1618_idx'),
        ),
    ]
