# Generated by Django 5.2.17 on 2026-09-16 16:13

import django.db.models.deletion
import django.utils.timezone
import shared.ids
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_default_mrp'),
        ('inventory', '0002_row_level_security_and_append_only'),
        ('pharmacy', '0003_row_level_security'),
        ('practitioners', '0002_row_level_security'),
        ('tenancy', '0003_branch_licence_authority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NarcoticRegisterBalance',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['item', 'batch'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'branch', 'item', 'batch'), name='pharmacy_one_register_balance_per_batch', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='NarcoticRegisterEntry',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('opening', 'Opening balance'), ('receipt', 'Received from supplier'), ('dispensed', 'Dispensed to a patient'), ('return_in', 'Returned by a patient'), ('return_out', 'Returned to supplier'), ('destroyed', 'Destroyed or written off'), ('adjustment', 'Adjustment after a physical count'), ('correction', 'Correction of an earlier entry')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=18)),
                ('occurred_on', models.DateField(help_text='The business date, which may not be today.')),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('patient_address', models.CharField(blank=True, max_length=300)),
                ('patient_identity_number', models.CharField(blank=True, help_text='Citizenship or other identity document shown.', max_length=60)),
                ('prescriber_name', models.CharField(blank=True, max_length=200)),
                ('prescriber_registration_number', models.CharField(blank=True, max_length=60)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=60)),
                ('dispensed_by_name', models.CharField(blank=True, max_length=200)),
                ('dispensed_by_registration_number', models.CharField(blank=True, help_text="The pharmacist's council registration.", max_length=60)),
                ('witness_name', models.CharField(blank=True, help_text='Required for destruction and adjustments.', max_length=200)),
                ('signature_reference', models.CharField(blank=True, max_length=300)),
                ('document_type', models.CharField(blank=True, max_length=60)),
                ('document_id', models.CharField(blank=True, max_length=64)),
                ('document_number', models.CharField(blank=True, max_length=60)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.branch')),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrected_by', to='pharmacy.narcoticregisterentry')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.location')),
                ('prescriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='practitioners.practitioner')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='register_entries', to='pharmacy.prescription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'narcotic register entries',
                'ordering': ['occurred_on', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'branch', 'item', 'occurred_on'], name='pharmacy_na_tenant__18c60b_idx'), models.Index(fields=['tenant', 'item', 'batch'], name='pharmacy_na_tenant__c39c92_idx'), models.Index(fields=['tenant', 'document_type', 'document_id'], name='pharmacy_na_tenant__f7905a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='pharmacy_register_entry_is_not_zero')],
            },
        ),
    ]
