# Generated by Django 5.2.17 on 2026-09-16 10:43

import django.db.models.deletion
import django.utils.timezone
import shared.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSeries',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=60)),
                ('fiscal_year', models.CharField(help_text='As written on documents: 2082/83', max_length=9)),
                ('pattern', models.CharField(max_length=100)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('first_issued_at', models.DateTimeField(blank=True, null=True)),
                ('last_issued_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'number series',
                'ordering': ['branch', 'document_type', 'fiscal_year'],
            },
        ),
        migrations.CreateModel(
            name='NumberRange',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=64)),
                ('start_number', models.PositiveIntegerField()),
                ('end_number', models.PositiveIntegerField()),
                ('next_number', models.PositiveIntegerField()),
                ('released_at', models.DateTimeField(blank=True, help_text='When the device gave the rest of the block back.', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranges', to='numbering.numberseries')),
            ],
            options={
                'ordering': ['series', 'start_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='numberseries',
            constraint=models.UniqueConstraint(fields=('tenant', 'branch', 'document_type', 'fiscal_year'), name='numbering_one_series_per_branch_year'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.UniqueConstraint(fields=('tenant', 'series', 'start_number'), name='numbering_unique_range_start'),
        ),
        migrations.AddConstraint(
            model_name='numberrange',
            constraint=models.CheckConstraint(condition=models.Q(('end_number__gte', models.F('start_number'))), name='numbering_range_is_not_backwards'),
        ),
    ]
