# Generated by Django 5.2.17 on 2026-09-16 17:17

import django.db.models.deletion
import django.utils.timezone
import shared.ids
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0002_row_level_security'),
        ('tenancy', '0003_branch_licence_authority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=10)),
                ('business_date', models.DateField(help_text='The day this shift is counted against.')),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_float', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('counted_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('variance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('variance_reason', models.CharField(blank=True, max_length=300)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='tenancy.branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='The counter this till sits on.', on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='tenancy.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-business_date', '-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('float_in', 'Float added'), ('petty_expense', 'Petty expense'), ('banked', 'Taken to the bank'), ('drop', 'Moved to the safe'), ('correction', 'Correction')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.CharField(max_length=300)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('witness_name', models.CharField(blank=True, max_length=200)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='payments.cashiershift')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DenominationCount',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='payments.cashiershift')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=60)),
                ('name_ne', models.CharField(blank=True, max_length=60)),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('wallet', 'Digital wallet'), ('qr', 'QR'), ('bank_transfer', 'Bank transfer'), ('cheque', 'Cheque'), ('credit', 'On account')], max_length=20)),
                ('requires_reference', models.BooleanField(default=False)),
                ('gives_change', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('in', 'Received'), ('out', 'Paid out')], db_index=True, max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tendered_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('change_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('document_type', models.CharField(blank=True, max_length=60)),
                ('document_id', models.CharField(blank=True, max_length=64)),
                ('document_number', models.CharField(blank=True, max_length=60)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('received_on', models.DateField(help_text='The business date, which may not be today.')),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.branch')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='parties.party')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='payments.payment')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.cashiershift')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.paymentmode')),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['tenant', 'branch', '-business_date'], name='payments_ca_tenant__dc2c95_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('tenant', 'location'), name='payments_one_open_shift_per_location'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='payments_cash_movement_is_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='denominationcount',
            constraint=models.UniqueConstraint(fields=('tenant', 'shift', 'value'), name='payments_one_count_per_denomination'),
        ),
        migrations.AddConstraint(
            model_name='paymentmode',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='payments_unique_mode_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'document_type', 'document_id'], name='payments_pa_tenant__f2c743_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'branch', '-received_on'], name='payments_pa_tenant__15f8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'shift'], name='payments_pa_tenant__e24916_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_amount_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('change_amount__gte', 0)), name='payments_change_not_negative'),
        ),
    ]
