# Generated by Django 5.2.17 on 2026-09-15 18:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import shared.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('name_ne', models.CharField(blank=True, max_length=200)),
                ('pan', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='PAN must be exactly 9 digits.', regex='^\\d{9}$')], verbose_name='PAN')),
                ('is_vat_registered', models.BooleanField(default=False)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('ird_office', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'legal entities',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, digits and hyphens; start and end with a letter or digit.', regex='^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'), django.core.validators.MinLengthValidator(3)])),
                ('name', models.CharField(max_length=200)),
                ('name_ne', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('trial', 'Trial'), ('active', 'Active'), ('grace', 'Grace period'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='provisioning', max_length=20)),
                ('tier', models.CharField(choices=[('pooled', 'Pooled database'), ('silo', 'Dedicated database'), ('on_prem', 'Customer premises')], default='pooled', max_length=20)),
                ('default_language', models.CharField(default='en', max_length=5)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=40)),
                ('trial_ends_on', models.DateField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_reason', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Short code used in document numbers.', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('name_ne', models.CharField(blank=True, max_length=200)),
                ('ward_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dda_licence_number', models.CharField(blank=True, max_length=50)),
                ('dda_licence_expiry', models.DateField(blank=True, null=True)),
                ('is_warehouse', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.district')),
                ('local_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.locallevel')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.province')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='tenancy.legalentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'branches',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='legalentity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('disabled', 'Disabled')], default='invited', max_length=20)),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('counter', 'Sales counter'), ('store', 'Store room'), ('rack', 'Rack'), ('shelf', 'Shelf'), ('bin', 'Bin'), ('cold_room', 'Cold room'), ('fridge', 'Refrigerator'), ('freezer', 'Freezer'), ('locked_cabinet', 'Locked cabinet'), ('ward', 'Ward'), ('ot', 'Operating theatre'), ('warehouse', 'Warehouse')], max_length=20)),
                ('temperature_zone', models.CharField(choices=[('ambient', 'Ambient'), ('cool', 'Cool (8-15°C)'), ('cold', 'Cold (2-8°C)'), ('frozen', 'Frozen (below 0°C)')], default='ambient', max_length=10)),
                ('is_sellable', models.BooleanField(default=True, help_text='Stock here can be sold. Quarantine locations set this to false.')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='tenancy.branch')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tenancy.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['branch', 'code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'branch', 'code'), name='tenancy_unique_location_code_per_branch')],
            },
        ),
        migrations.AddConstraint(
            model_name='legalentity',
            constraint=models.UniqueConstraint(fields=('tenant', 'pan'), name='tenancy_unique_pan_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='tenancy_unique_branch_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='tenantdomain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('tenant',), name='tenancy_one_primary_domain_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='tenancy_unique_membership'),
        ),
    ]
