# Generated by Django 5.2.17 on 2026-09-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_row_level_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='dda_licence_authority',
            field=models.CharField(blank=True, help_text='The office that issued the licence: the province, or DDA centrally.', max_length=120),
        ),
    ]
