# Generated by Django 5.2.17 on 2026-09-16 15:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import shared.ids
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_unit_plural_label'),
        ('parties', '0001_initial'),
        ('tenancy', '0003_branch_licence_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, help_text='Assigned when posted.', max_length=60)),
                ('supplier_invoice_number', models.CharField(max_length=60)),
                ('supplier_invoice_date', models.DateField()),
                ('received_on', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=300)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.branch')),
                ('location', models.ForeignKey(help_text='Where the delivery is put away.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.location')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='parties.party')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.UUIDField(default=shared.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('free_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Price of one pack.', max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('batch_number', models.CharField(blank=True, max_length=60)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.item')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.goodsreceipt')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('unit', models.ForeignKey(help_text='The pack this was bought in, such as a box of 100.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.unitofmeasure')),
            ],
            options={
                'ordering': ['receipt', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['tenant', 'branch', '-received_on'], name='purchasing__tenant__03c693_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['tenant', 'supplier', '-received_on'], name='purchasing__tenant__fb17db_idx'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.UniqueConstraint(fields=('tenant', 'supplier', 'supplier_invoice_number'), name='purchasing_one_receipt_per_supplier_invoice'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchasing_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('free_quantity__gte', 0)), name='purchasing_free_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='purchasing_rate_not_negative'),
        ),
    ]
